### PR TITLE
Skip test2

### PR DESCRIPTION
**Pull request by MartaSzel**
Added SKIP option.

### CODE REVIEW

**Comment by pietrushnic** [comment]
@MartaSzel @artur-rs commit messages are not very informative

**Comment by MartaSzel** [comment]
Changes from https://github.com/robotframework/robotframework/pull/2317/files#diff-10e2c31877704584a1d5aaf840d45601

**Review by artur-rs — APPROVED** [review]

**Comment by sulewskiprzemyslaw** [comment]
@macpijan for the current I will leave open this PR - maybe someday we might rebase it and prepare the new upstream PR

**Comment by macpijan** [comment]
It's in this "maybe" state for 4 years already.

Haven't you mentioned that the SKIP option was already added in more recent RF releases?

**Comment by sulewskiprzemyslaw** [comment]
According to the docs, SKIP is available from RF 4.0. Taking this into account, I close the issue

**Pull request closed without merging**
